package com.lifehelper;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lifehelper.RouteLineNodeTable;
import com.lifehelper.PlanNodeTable;

import com.lifehelper.RouteLineNodeTableDao;
import com.lifehelper.PlanNodeTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig routeLineNodeTableDaoConfig;
    private final DaoConfig planNodeTableDaoConfig;

    private final RouteLineNodeTableDao routeLineNodeTableDao;
    private final PlanNodeTableDao planNodeTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        routeLineNodeTableDaoConfig = daoConfigMap.get(RouteLineNodeTableDao.class).clone();
        routeLineNodeTableDaoConfig.initIdentityScope(type);

        planNodeTableDaoConfig = daoConfigMap.get(PlanNodeTableDao.class).clone();
        planNodeTableDaoConfig.initIdentityScope(type);

        routeLineNodeTableDao = new RouteLineNodeTableDao(routeLineNodeTableDaoConfig, this);
        planNodeTableDao = new PlanNodeTableDao(planNodeTableDaoConfig, this);

        registerDao(RouteLineNodeTable.class, routeLineNodeTableDao);
        registerDao(PlanNodeTable.class, planNodeTableDao);
    }
    
    public void clear() {
        routeLineNodeTableDaoConfig.getIdentityScope().clear();
        planNodeTableDaoConfig.getIdentityScope().clear();
    }

    public RouteLineNodeTableDao getRouteLineNodeTableDao() {
        return routeLineNodeTableDao;
    }

    public PlanNodeTableDao getPlanNodeTableDao() {
        return planNodeTableDao;
    }

}
